#! /bin/sh

pgrep -x sxhkd >/dev/null || sxhkd &

bspc monitor -d 1 2 3 4 5

bspc config border_width 3
bspc config window_gap 8
bspc config focused_border_color "#007b0f"
bspc config presel_feedback_color "#cc6666"

bspc config split_ratio 0.50
bspc config borderless_monocle true
bspc config gapless_monocle true
bspc config pointer_modifier mod1
bspc config focus_follows_pointer true
#---------------------------------------
############### AutoStart
#---------------------------------------

## Keyboard ##
#
sxhkd &

## NetworkManager Applet Set ##
#
nm-applet &

## Power saving ##
#
xfce4-power-manager &

## Authentication Agent ##
#
/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &

## Notification deamon ##
#
dunst --config ~/.config/dunst/dunstrc &

## Adding Sound ##
#
pipewire &

## Wallpaper Set ##
#
feh --bg-fill --randomize ~/Pictures/wallp/ &

## Screen Rez ##
#
~/.config/screenlayout/display.sh &

## Auto Mount USB ##
#
devmon &

## Cursor ##
#
xsetroot -cursor_name left_ptr &

## Compositor ##
#
picom --config ~/.config/picom/picom.conf &

## Top Bar ##
#
polybar &
